/*============================================================================
    Data Module
 ============================================================================*/

function getShortDate(){
    return ((new Date()).toISOString().substring(0,10));
}

function getISODate(){
    return (new Date()).toISOString();
}

function getData(options){

    let config = {
        "USERNAME" : options.USERNAME || "test6@a.b",
        "MAIN_FISHER" : options.MAIN_FISHER || "test_fisher6",
        "TODAY_DATE" : options.TODAY_DATE,
        "FAKE_TRIP_ID" : options.FAKE_TRIP_ID,
        "SPECIES_KEY" : options.SPECIES_KEY || 'snoek',
        "SPECIES_LABEL" : options.SPECIES_LABEL || 'Snoek',
        "BAIT_KEY" : options.BAIT_KEY || 'sardine',
        "CATCH_COOP_WEIGHT" : options.CATCH_COOP_WEIGHT || 300
    };

    console.log("POST CONFIG: \n" + JSON.stringify(config, null, 4));


    let MAIN_DATA = [ { '*meta-model-version*': 2016102811,
        '*meta-submission-date*': config.TODAY_DATE,
        comment_has: 'no',
        comment_has_pic2: null,
        cost_fuel_price: 1400,
        cost_has: 'yes',
        crew_members: null,
        current_direction: null,
        fisher_community_province: 'WC',
        fuel_litres: 108,
        income_note: null,
        no_catch_reason: null,
        no_trip_reason_other: null,
        shore_type: null,
        target_specie_list: null,
        time_end: '14:03:00.000Z',
        trip_community: 'democommunity',
        trip_community_selected_shore: null,
        trip_community_shore: null,
        trip_date: getShortDate(),
        wind_direction: 'wind_southeast',
        rpt_catch:
            [ { alloc_coop_crates: 0,
                alloc_coop_number: null,
                alloc_coop_weight_kg: config.CATCH_COOP_WEIGHT,
                alloc_self_crates: null,
                alloc_self_crates_multiple: null,
                alloc_self_crates_single: null,
                alloc_self_number: null,
                alloc_self_number_multiple: null,
                alloc_self_number_single: null,
                alloc_self_weight_kg: null,
                alloc_self_weight_kg_multiple: null,
                alloc_self_weight_kg_single: null,
                alloc_sold_other_crates: null,
                alloc_sold_other_number: null,
                alloc_sold_other_weight_kg: 101,
                catch_bait: config.BAIT_KEY,
                catch_bait_other: null,
                catch_crates: null,
                catch_number: 40,
                catch_string: '401 kg',
                catch_string_crates: null,
                catch_string_join_a: null,
                catch_string_join_b: null,
                catch_string_number: null,
                catch_string_weight_kg: '401 kg',
                catch_weight_kg: 401,
                coop_price_per_batch: null,
                coop_price_per_crate: null,
                coop_price_per_item: null,
                coop_price_per_kg: null,
                coop_price_type: null,
                income: '12832',
                income_coop: '0',
                income_coop_crate: null,
                income_coop_item: null,
                income_coop_kg: null,
                income_other: '12832',
                income_other_crate: null,
                income_other_item: null,
                income_other_kg: '12832',
                note_alloc: null,
                note_no_crates: null,
                note_no_crates2: null,
                note_no_number: null,
                note_no_number2: null,
                note_no_weight: null,
                note_no_weight2: null,
                note_not_wclobster: null,
                note_not_wclobster2: null,
                note_specie_income: null,
                other_price_per_batch: null,
                other_price_per_crate: null,
                other_price_per_item: null,
                other_price_per_kg: 32,
                other_price_type: 'per_kg',
                selected_specie: config.SPECIES_KEY,
                selected_specie_label: config.SPECIES_LABEL } ],
        cost_other_name: null,
        comment_image: null,
        'geopoint:Altitude': null,
        comment_image3: null,
        nonlinked_boat_reg_type: null,
        'geopoint:Longitude': null,
        instanceID: 'uuid:faketrip' + config.FAKE_TRIP_ID,
        nonlinked_boat_reg_num: null,
        cost_transport: null,
        permit_list_boat: [ 'permit_comm_tlf' ],
        catch_specie_manual: null,
        trip_from_hometown_boat: 'yes',
        cost_harbour_fee: 50,
        trip_community_boat: 'struisbaai',
        '*meta-date-marked-as-complete*': getISODate(),
        deviceid: '356545061648014',
        fisher_community: 'democommunity',
        trip_type: 'boat',
        start: getShortDate() + 'T19:02:28.673Z',
        trip_today_or_prev: 'today',
        'geopoint:Accuracy': null,
        nonlinked_boat_owner_manual: null,
        permit_list_self: null,
        trip_from_hometown_shore: null,
        wind_strength: 'wind_littlewind',
        '*meta-is-complete*': true,
        target_specie_manual: null,
        current_has: 'no',
        today: getShortDate(),
        sea_condition: 'sea_calm',
        trip_from_hometown_notrip: null,
        displayed_profit: '10482',
        comment_has_pic3: null,
        rpt_catch_count: '1',
        all_or_self_only_selected: 'whole_boat',
        '*meta-instance-id*': 'uuid:faketrip' + config.FAKE_TRIP_ID,
        trip_date_manual: null,
        boat_skipper_manual: 'Petrus',
        note_costs1: null,
        time_start: '03:00:00.000Z',
        boat_as_per_profile: 'yes',
        comment_text: null,
        cost_oil: null,
        comment_image2: null,
        cost_note: null,
        trip_has: 'yes',
        count_repeats: '1',
        num_irp: null,
        phonenumber: null,
        '*meta-ui-version*': null,
        cost_total: '2350',
        weather: 'weather_sunny',
        note_costs2: null,
        yesno_label: 'Ja',
        catch_method_list: [ 'handline' ],
        cost_food: 50,
        trip_community_province_boat: null,
        income_total: '12832',
        trip_community_selected_notrip: null,
        calc_form_language: 'Afrikaans',
        end: getShortDate() + 'T19:13:21.606Z',
        shore_spots: null,
        selected_community_label: 'Demo Community',
        trip_community_province_shore: null,
        nonlinked_boat_type: null,
        trip_community_selected_boat: null,
        crew_number: 8,
        current_strength: null,
        nonlinked_boat_name: null,
        catch_specie_list: [ config.SPECIES_KEY ],
        landing_site: 'struisbaai_harbour',
        username: config.USERNAME,
        main_fisher: config.MAIN_FISHER,
        catch_has: 'yes',
        'geopoint:Latitude': null,
        profit_note: null,
        trip_community_province_notrip: null,
        no_trip_reason: null,
        note_date: null,
        cost_other: null,
        cost_bait: 850,
        all_or_self_only: 'whole_boat' } ];

    let MAIN_DATA_2 = [
        {
            "fuel_litres": null,
            "trip_community": "democommunity",
            "trip_date": getShortDate(),
            "crew_members": null,
            "shore_type": "shoreline",
            "current_direction": null,
            "no_trip_reason_other": null,
            "trip_community_shore": "democommunity",
            "comment_has": "no",
            "trip_community_selected_shore": null,
            "*meta-model-version*": 2017033100,
            "cost_has": "no",
            "fisher_community_province": "WC",
            "income_note": null,
            "wind_direction": "wind_south",
            "time_end": "08:44:00.000Z",
            "no_catch_reason": null,
            "comment_has_pic2": null,
            "target_specie_list": null,
            "cost_fuel_price": null,
            "rpt_catch": [
                {
                    "income_other": "0",
                    "catch_number": null,
                    "catch_string_weight_kg": "200 kg",
                    "alloc_self_number_multiple": null,
                    "alloc_sold_other_crates": null,
                    "income_coop_kg": "1000",
                    "alloc_self_weight_kg_single": 100,
                    "income_coop_item": null,
                    "note_no_crates": null,
                    "alloc_self_crates": null,
                    "income_other_kg": null,
                    "income_coop": "1000",
                    "alloc_coop_crates": null,
                    "alloc_self_weight_kg_multiple": null,
                    "income": "1000",
                    "note_specie_income": null,
                    "coop_price_per_crate": null,
                    "note_no_weight2": null,
                    "alloc_self_number": null,
                    "catch_string_join_b": null,
                    "catch_weight_kg": 200,
                    "other_price_per_batch": null,
                    "catch_bait": "none",
                    "alloc_self_number_single": null,
                    "coop_price_type": "per_kg",
                    "coop_price_per_item": null,
                    "selected_specie": config.SPECIES_KEY,
                    "alloc_self_crates_multiple": null,
                    "alloc_coop_number": null,
                    "catch_string": "200 kg",
                    "alloc_coop_weight_kg": config.CATCH_COOP_WEIGHT,
                    "income_other_item": null,
                    "other_price_per_crate": null,
                    "note_not_wclobster2": null,
                    "selected_specie_label": config.SPECIES_LABEL,
                    "catch_string_join_a": null,
                    "catch_bait_other": null,
                    "coop_price_per_kg": 10,
                    "coop_price_per_batch": null,
                    "alloc_sold_other_weight_kg": null,
                    "catch_string_crates": null,
                    "alloc_self_crates_single": null,
                    "other_price_type": null,
                    "income_other_crate": null,
                    "other_price_per_kg": null,
                    "alloc_self_weight_kg": "100",
                    "note_no_number": null,
                    "catch_crates": null,
                    "alloc_sold_other_number": null,
                    "note_no_weight": null,
                    "note_no_number2": null,
                    "note_not_wclobster": null,
                    "catch_string_number": null,
                    "note_no_crates2": null,
                    "income_coop_crate": null,
                    "note_alloc": null,
                    "other_price_per_item": null
                }
            ],
            "cost_other_name": null,
            "comment_image": null,
            "geopoint:Altitude": null,
            "comment_image3": null,
            "nonlinked_boat_reg_type": null,
            "geopoint:Longitude": null,
            "instanceID": 'uuid:faketrip' + config.FAKE_TRIP_ID,
            "nonlinked_boat_reg_num": null,
            "cost_transport": null,
            "permit_list_boat": null,
            "catch_specie_manual": null,
            "trip_from_hometown_boat": null,
            "cost_harbour_fee": null,
            "trip_community_boat": null,
            '*meta-date-marked-as-complete*': getISODate(),
            "deviceid": "357657075118154",
            "fisher_community": "democommunity",
            "trip_type": "shore",
            "start": getShortDate() + 'T19:02:28.673Z',
            "trip_today_or_prev": "today",
            "geopoint:Accuracy": null,
            "nonlinked_boat_owner_manual": null,
            "permit_list_self": [
                "permit_irp_exempt"
            ],
            "trip_from_hometown_shore": "yes",
            "wind_strength": "wind_littlewind",
            "*meta-is-complete*": true,
            "target_specie_manual": null,
            "current_has": "no",
            "today": getShortDate(),
            "sea_condition": "sea_calm",
            "trip_from_hometown_notrip": null,
            "displayed_profit": "1000",
            "comment_has_pic3": null,
            "rpt_catch_count": "1",
            "all_or_self_only_selected": null,
            "*meta-instance-id*": 'uuid:faketrip' + config.FAKE_TRIP_ID,
            "trip_date_manual": null,
            "boat_skipper_manual": null,
            "note_costs1": null,
            "time_start": "03:00:00.000Z",
            "boat_as_per_profile": null,
            "comment_text": null,
            "cost_oil": null,
            "comment_image2": null,
            "cost_note": null,
            "trip_has": "yes",
            "count_repeats": "1",
            "num_irp": null,
            "phonenumber": null,
            "*meta-ui-version*": null,
            "cost_total": "0",
            "weather": "weather_cloudy",
            "note_costs2": null,
            "yesno_label": "Yes",
            "catch_method_list": [
                "hand"
            ],
            "cost_food": null,
            "trip_community_province_boat": null,
            "income_total": "1000",
            "trip_community_selected_notrip": null,
            "calc_form_language": "English",
            "end": getShortDate() + 'T19:13:21.606Z',
            "shore_spots": "Test",
            "selected_community_label": "Demo Community",
            "trip_community_province_shore": null,
            "nonlinked_boat_type": null,
            "trip_community_selected_boat": null,
            "crew_number": null,
            "current_strength": null,
            "nonlinked_boat_name": null,
            "catch_specie_list": [ config.SPECIES_KEY ],
            "landing_site": null,
            "username": config.USERNAME,
            "main_fisher": config.MAIN_FISHER,
            "catch_has": "yes",
            "geopoint:Latitude": null,
            "profit_note": null,
            "trip_community_province_notrip": null,
            "no_trip_reason": null,
            "note_date": null,
            "cost_other": null,
            "cost_bait": null,
            "*meta-submission-date*": config.TODAY_DATE,
            "all_or_self_only": "self_only"
        }
    ];

    return MAIN_DATA_2;
}

module.exports = {
    getData: getData
};

